import type { Article } from './types'

export const SEED_ARTICLES: Article[] = [
  {
    id: 'article-1',
    topic: 'XMPP',
    title: 'Why peer discovery should feel invisible',
    subtitle: 'A practical design argument for hiding transport complexity without hiding trust.',
    summary: 'A practical design argument for hiding transport complexity without hiding trust.',
    coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=620&h=260&fit=crop&auto=format',
    blocks: [
      {
        id: 'a1b1',
        type: 'paragraph',
        content: 'When you open a messaging app, you expect to find your friends. You do not expect to think about DHT routing, peer discovery, or NAT traversal. Yet for decentralized networks, these concerns have historically leaked into the user experience.',
      },
      {
        id: 'a1b2',
        type: 'heading',
        content: 'The invisible discovery problem',
      },
      {
        id: 'a1b3',
        type: 'paragraph',
        content: 'Every peer-to-peer system must solve the discovery problem: how do you find other participants without a central directory? The answer has traditionally been some combination of DHT lookups, mDNS, or relay nodes. But from a user perspective, none of this should matter.',
      },
      {
        id: 'a1b4',
        type: 'quote',
        content: 'Good design hides complexity. Great design hides the fact that there was ever complexity to hide.',
        meta: { attribution: 'Unknown' },
      },
      {
        id: 'a1b5',
        type: 'paragraph',
        content: 'Our approach treats peer discovery as a solved infrastructure problem. The application layer exposes only signals that matter to the user: who is online, what communities exist, and whether a connection is trustworthy. The network topology is irrelevant.',
      },
    ],
    author: {
      name: 'Maren Holdt',
      handle: 'maren',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=64&h=64&fit=crop&auto=format',
      verified: true,
    },
    createdAt: '2026-06-25T10:00:00Z',
    updatedAt: '2026-06-25T10:00:00Z',
    publishedAt: '2026-06-25T10:00:00Z',
    readTime: '6 min read',
    slug: 'why-peer-discovery-should-feel-invisible',
    status: 'published',
    visibility: 'public',
    settings: {
      allowReplies: true,
      showReadingTime: true,
      notifyFollowers: true,
      addToProfile: true,
    },
  },
  {
    id: 'article-2',
    topic: 'XMPP',
    title: 'Building a peer-first XMPP client',
    subtitle: 'What changes when the network is local-first and intermittently connected.',
    summary: 'What changes when the network is local-first and intermittently connected.',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=620&h=260&fit=crop&auto=format',
    blocks: [
      {
        id: 'a2b1',
        type: 'paragraph',
        content: 'A peer-first client changes more than transport. It changes how identity, trust and availability are explained to people.',
      },
      {
        id: 'a2b2',
        type: 'heading',
        content: 'Discovery without a directory',
      },
      {
        id: 'a2b3',
        type: 'paragraph',
        content: 'The interface should expose confidence and provenance, not routing internals. Readers need to understand why a person or community appeared without learning the mechanics of the DHT.',
      },
      {
        id: 'a2b4',
        type: 'paragraph',
        content: 'This requires rethinking the contact model. Instead of a server-authoritative roster, we use capability discovery and signed identity announcements. Trust is established through cryptographic verification, not platform endorsement.',
      },
      {
        id: 'a2b5',
        type: 'quote',
        content: 'The most important design principle: never ask the user a question the system can answer for itself.',
      },
    ],
    author: {
      name: 'Elif Şahin',
      handle: 'elif_dev',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=64&h=64&fit=crop&auto=format',
    },
    createdAt: '2026-06-26T14:00:00Z',
    updatedAt: '2026-06-26T14:00:00Z',
    publishedAt: '2026-06-26T14:00:00Z',
    readTime: '6 min read',
    slug: 'building-a-peer-first-xmpp-client',
    status: 'published',
    visibility: 'public',
    settings: {
      allowReplies: true,
      showReadingTime: true,
      notifyFollowers: true,
      addToProfile: true,
    },
  },
  {
    id: 'article-3',
    topic: 'IDENTITY',
    title: 'Designing trust into decentralised identity',
    subtitle: 'A reader-first model for identity, verification and recovery.',
    summary: 'A reader-first model for identity, verification and recovery.',
    blocks: [
      {
        id: 'a3b1',
        type: 'paragraph',
        content: 'Identity in a decentralised system is fundamentally different from identity on a platform. On a platform, identity is delegated. In a P2P network, identity must be self-sovereign — owned and controlled by the individual.',
      },
      {
        id: 'a3b2',
        type: 'heading',
        content: 'Verification without authority',
      },
      {
        id: 'a3b3',
        type: 'paragraph',
        content: 'Without a central authority to verify identity claims, we need cryptographic primitives that speak for themselves. A keypair is the identity. Everything else — display names, avatars, profile data — is attested metadata.',
      },
      {
        id: 'a3b4',
        type: 'code',
        content: 'const identity = await createIdentity()\nconsole.log(identity.fingerprint)\n// "3a1b...9f2d" — this is the canonical identifier',
        meta: { language: 'typescript' },
      },
    ],
    author: {
      name: 'Theo Nguyen',
      handle: 'theo_n',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop&auto=format',
    },
    createdAt: '2026-06-24T08:00:00Z',
    updatedAt: '2026-06-24T08:00:00Z',
    publishedAt: '2026-06-24T08:00:00Z',
    readTime: '6 min read',
    slug: 'designing-trust-into-decentralised-identity',
    status: 'published',
    visibility: 'public',
    settings: {
      allowReplies: true,
      showReadingTime: true,
      notifyFollowers: true,
      addToProfile: true,
    },
  },
  {
    id: 'article-4',
    topic: 'COMMUNITIES',
    title: 'Local-first communities need durable publishing',
    subtitle: 'Why articles and discussions should be separate but connected.',
    summary: 'Why articles and discussions should be separate but connected.',
    blocks: [
      {
        id: 'a4b1',
        type: 'paragraph',
        content: 'Communities on P2P networks face a unique challenge: how do you publish durable content when the network is ephemeral? Traditional forums assume always-on servers. Local-first communities need a different model.',
      },
      {
        id: 'a4b2',
        type: 'heading',
        content: 'Articles as durable objects',
      },
      {
        id: 'a4b3',
        type: 'paragraph',
        content: 'An article should outlive the conversation it starts. By separating long-form content from the discussion thread, we create a referenceable object that persists regardless of chat activity.',
      },
    ],
    author: {
      name: 'Elif Şahin',
      handle: 'elif_dev',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=64&h=64&fit=crop&auto=format',
    },
    createdAt: '2026-06-23T16:00:00Z',
    updatedAt: '2026-06-23T16:00:00Z',
    publishedAt: '2026-06-23T16:00:00Z',
    readTime: '4 min read',
    slug: 'local-first-communities-need-durable-publishing',
    status: 'published',
    visibility: 'public',
    settings: {
      allowReplies: true,
      showReadingTime: true,
      notifyFollowers: true,
      addToProfile: true,
    },
  },
]
